### ISSUE TITLE
Slow bounce-back to usage of resources after stress

### ISSUE THREAD

**Issue by miocrime** [mhx/dwarfs#124]
Example: I start the compression of a 10gib file.

I then start a separate compression of a 2gib file.

The system will be in stress from having to use almost all resources.

The compression of the 2gib file finishes.

The compression of the 10gib stays at the same speed for a while as if the system were still in stress. The segmentation and compression speed gradually speeds back up in a slow manner, for 30 minutes - an hour the compression speed can be slowed down by the now gone stress situation.

Of course, this is based on what it feels slow to me comparatively. I haven't done a recorded comparison.

**Comment by mhx** [comment]
This seems a little odd and right now I don't have a good idea what the cause could be.

If the file system build is slower than expected (i.e. not using as many compression threads as configured) it's usually because the input stages (ordering & segmentation) don't output data at a high enough rate. These both run in their own threads and my hope so far has been that as compression threads run out of work, more CPU time is available for the input stages. I think at some point I experimented with setting thread priorities explicitly, but that didn't seem to make enough of a difference to add more complexity to the code.

However, I made some changes (included in 0.7.0-RC4) that show a separate `ordering1` thread for as long as ordering is not complete. So you should be able to see `ordering1`, `blockify1` (segmentation) as well as several `compressN` threads in a process monitor (e.g. `htop`). Also, I've added a new option `--compress-niceness` that will nice the compression threads by 5 priority levels by default (setting this to 0 is equivalent to the current behaviour). In a quick experiment, the new default was about 2% faster than the original behaviour.

If you could try your experiment again and check how much CPU is being used by the different threads we might get a better understanding of what you're seeing.

The `ordering1` thread should stay close to using a full core for as long as it's running (and while CPU resources are available). The `blockify1` thread can be blocked either by `ordering1` not outputting new inodes fast enough or by too many blocks in the queue waiting for compression. So if `--num-workers` compression threads are running, it's perfectly fine for `blockify1` to stay idle. The `--memory-limit` option determines how many blocks are can be flight before `blockify1` blocks temporarily.

> I start the compression of a 10gib file.
>
> I then start a separate compression of a 2gib file.

Can you elaborate on that? Are you trying to compress *single files* of these sizes? I.e., each output filesystem contains only a single, huge file?

**Comment by mhx** [comment]
> I should mention that I use high settings for -B(24-30) and -S(24-26) when I want to reach good ratios and that increases system resource usage.

Ah yes, especially the high `-B` settings will slow down the segmentation thread. This means it'll be slower to provide blocks to the compressors. And depending on how well segmentation can find duplicate segments, it potentially won't be able to keep all compression threads busy. This may change over time, regardless of whether you're running a separate process in parallel. So this *may* be what you're seeing.

**Comment by mhx** [comment]
Ok, I'm pretty certain what you're seeing is just the segmenter/blockifier being too slow to keep the compressors busy. Can you give some details on the system you're running this on (most importantly number of CPU cores)?

I've tried this on an 8-core Xeon E-2286M (i.e. 16 virtual cores). Here's what it looks like with "default" options (`-l7 -B1`):

![mkdwarfs-l7-B1](https://user-images.githubusercontent.com/301215/209921694-15a40d50-0132-4fd6-9474-b5ac91694d78.png)

You can see how around 35 seconds, the compressors ramp up working on 14 (virtual) cores while `ordering` and `blockify` are occupying the remaining 2 cores. Once the queue between the segmenter and the compressors is full, `blockify` stops and another compressor thread takes over. `ordering` is finished around the 90 second mark, at which point all cores are dedicated to segmenting/compression. So this is what you'd typically expect.

Running a second `mkdwarfs` process in parallel doesn't change much:

![mkdwarfs-l7-B1-parallel-2](https://user-images.githubusercontent.com/301215/209922405-1d32d2fe-6a38-40c2-823d-b9de47c8a824.png)

You can see that as the second process finishes, the resources are immediately taken over by the first process.

Now, let's try again with `-l9 -B32`:

![mkdwarfs-l9-B32-L8g](https://user-images.githubusercontent.com/301215/209922681-df10ac54-4a70-4cf2-a9ed-6ee2eb64f824.png)

`-l9` uses 64 MiB blocks and LZMA compression. LZMA is typically faster than ZSTD at the highest compression level. Additionally, the `-B32` means *a lot* more lookups for the segmenter. You can see that where before the `blockify` thread was only active about 50% of the time, it is now constantly occupying a full core. It still doesn't produce enough output to keep the compressors busy, so only about 6 compression threads are active at the same time. However, this is not a constant pattern, as both the segmenter and compressors don't work at constant speed and the more data the segmenter can save, the less work there remains for the compressors.

Feel free to play around with this some more and add your comments, but I don't think there's an inherent problem here with `mkdwarfs`.
