### ISSUE TITLE
Mount time is way slow with new universe binary vs just a static binary of dwarfs

### ISSUE THREAD

**Issue by godane** [mhx/dwarfs#149]
So the new universe binary is slower then older static dwarfs from 0.7.0-RC4. So compiled dwarfs to see if its changes in 0.7.0 or not. Good news is a static dwarfs mounts like 0.7.0-RC4. I maybe the only one with this problem cause I'm using them on as part of Live OS on my SSD. The only way your going to test this is with 100 dwarfs being mount one after the other and compare between universe binary time vs static binary of dwarfs.

**Comment by Phantop** [comment]
I think this is because the provided universal binaries are compressed with `upx`. I found decompressing them made them much faster.

**Comment by mhx** [comment]
> So the new universe binary is slower then older static dwarfs from 0.7.0-RC4.

The "classic" static binaries are still available as before in the "Assets" section of the release page (e.g. [dwarfs-0.7.0-Linux-x86_64.tar.xz](https://github.com/mhx/dwarfs/releases/download/v0.7.0/dwarfs-0.7.0-Linux-x86_64.tar.xz)). The "universal" binaries are just a new option.

@Phantop is correct that the universal binaries have an additional decompression step due to `upx` compression that *definitely* takes extra time (around 250ms on my system). If that's an issue, then definitely either decompress the universal binary

```
upx -d dwarfs-universal-*
```

or just keep using the "classic" binaries.

**Comment by mhx** [comment]
I've updated the [README](https://github.com/mhx/dwarfs#universal-binaries) to address this. Let me know if you think that solves your problem!
