### ISSUE TITLE
Accept forwards compatibility

### ISSUE THREAD

**Issue by adminx01** [mhx/dwarfs#158]
Currently older dwarfs versions refuse to run images created in newer versions of it. This is a pretty annoying problem on GNU/Linux where decentralized distribution systems decide at different times to provide the updated version.

The update changelog doesn't seem groundbreaking enough to require this. Maybe its because of the new metadata method?

Anyway just wanted to let you know that this causes problems.

**Comment by mhx** [comment]
That's a very fair point.

The current behaviour of simply ruling out forward compatibility upon any change that could make an older binary fall over was just out of simplicity.

> Maybe its because of the new metadata method?

That and the new compression algo. The metadata change is in fact not forward-compatible because older Linux binaries wouldn't be able to properly handle images containing symbolic links created on Windows.

In any case, going forward I'm going to adopt "feature sets". As long as newer binaries create images using features that are a subset of the feature set provided by an older binary, the older binary will be able to load them.

**Comment by adminx01** [comment]
cool

**Comment by mhx** [comment]
Fixed in v0.7.3.
