### ISSUE TITLE
Add integrity check from dwarfsextract to mount as well

### ISSUE THREAD

**Issue by adminx01** [mhx/dwarfs#172]
I noticed that when extracting dwarfs detects if the image is incomplete/corrupt but not when mounting

**Comment by mhx** [comment]
If I add support for this (which is trivial), it will be an optional feature. The rationale being that the integrity check will dramatically increase mount times. (See also #48 for an extended discussion around slow mount times, read-ahead, and integrity checks.)

If it's an optional feature, however, it's not really that much different from running `dwarfsck` prior to running `dwarfs`.

Note that integrity checks *will* actually be performed by `dwarfs`, but only when a (corrupt/missing) block is accessed.

**Comment by mhx** [comment]
Please let me know if running `dwarfsck` is a viable solution for your use case, of if (and why) you'd prefer a new option for `dwarfs`.

**Comment by adminx01** [comment]
> If I add support for this (which is trivial), it will be an optional feature. The rationale being that the integrity check will dramatically increase mount times.

Well it felt kinda instant on extraction so I assumed it wouldn't slow down anything

**Comment by mhx** [comment]
> > If I add support for this (which is trivial), it will be an optional feature. The rationale being that the integrity check will dramatically increase mount times.
> 
> Well it felt kinda instant on extraction so I assumed it wouldn't slow down anything

It all depends. If the whole image is in the file system cache, the integrity check is blazingly fast. If it's a huge image that needs to be read from a spinning disk or from a slow USB drive, it can easily take tens of seconds or even minutes to complete.

**Comment by adminx01** [comment]
alright then i'll see if can make use of dwarfsck instead thanks

**Comment by mhx** [comment]
Just to give you an idea, here's mounting an 894 MiB DwarFS image on an NFS share over a slow WiFi connection, both without and with integrity check (which I just added as a test — as I said, it's a trivial change):

```
$ dwarfs /mnt/sauron/minecraft.dwarfs tmp -f 
I 18:43:09.951912 dwarfs (v0.7.2-218-g1aba214-dirty on branch mhx/categorizer, fuse version 35)
I 18:43:15.770834 file system initialized [5.819s]
```

```
$ dwarfs /mnt/sauron/minecraft.dwarfs tmp -f -ocheck_integrity
I 18:43:29.161048 dwarfs (v0.7.2-218-g1aba214-dirty on branch mhx/categorizer, fuse version 35)
I 18:47:34.290903 file system initialized [4.085m]
```

So with integrity checks it's about 40x slower, as the whole file needs to be read instead of just the metadata.

**Comment by mhx** [comment]
I'm not sure that's going to make much of a difference. In fact, the metadata block *is* integrity-checked, and it's essentially just a random block in the file system image, just like any other block.

Data corruption is typically either just a bit flip somewhere random or a larger chunk of data being broken/overwritten or otherwise corrupted. Both types of corruption are usually local, i.e. if you're not looking at the right spot, you're going to miss it. If the corruption would be like "noise", i.e. a randomly distributed set of bit flips, then it's highly unlikely that the metadata would be free from corruption (I've never come across anything like this, though).

Also, each block will typically be integrity-checked whenever it is accessed, so you can't (usually) read corrupted data from a DwarFS image. The exception being that when you pass `--disable-integrity-check` to `dwarfsextract`, it will bypass this check in order to try and recover as much data from a broken image as possible.
