### ISSUE TITLE
Kernel level implementation

### ISSUE THREAD

**Issue by shadichy** [mhx/dwarfs#186]
It would be a lot good if DwarFS has a native Linux kernel module (FUSE-independent). This would be hard I guess, as IIRC you don't wanna make one for some reasons. But within a kernel module, DwarFS usability and availability will spread across wider range of Linux distributions (including Android's and embedded systems)

**Comment by mhx** [comment]
Hi and thanks for your feedback.

With its rather long list of dependencies, the chances of DwarFS making it into the Linux kernel are pretty much zero.

As much as I'd like to see this happen, I neither have a strategy nor the resources to make this happen. At the moment, I'd much rather spend my time making DwarFS as useful as possible rather than fighting windmills. :)

This has come up before, so I'm going to merge this with the original thread.
