### ISSUE TITLE
null_decompressor not implemented (core dumped)

### ISSUE THREAD

**Issue by samuelwatsonofficial** [mhx/dwarfs#193]
I was attempting to recompress a previously compressed archive to a higher compression level and got an error some part of the way through. The command I used is below along with a paste of the error message.
mkdwarfs -i ibdocs.dwarfs -o ibdocs2.dwarfs --recompress --compress-level=9 
https://pastebin.com/hHybQj72
Since this error is spesific to recompression so far it is not a massive problem for me but I still hope it is a simple fix :).

**Comment by mhx** [comment]
Hi again! :)

Thanks for reporting this. This was *the* code path that I have obviously missed when I decided to get rid of the null decompressor in 0771e8aa7. I was certain this wasn't used anymore since it had no test coverage. Funnily enough, looking at the one code path that's still using it, I found a `TODO` saying that we shouldn't have to decompress uncompressed blocks.

I've reverted the commit for now and will take a closer look at getting rid of the null decompressor at a later point, as this will require a few more changes. I've also added a test case so the code will finally be covered.

I'll push out a v0.9.3 with the fix in the next few days.

**Comment by samuelwatsonofficial** [comment]
Thanks! I'm glad it was clear what the issue was and you have a fix in place, you are a very dedicated developer and you have responded to the bugs I found very quickly. Thank you so much for making this project and spending so much of your own time helping others.

**Comment by mhx** [comment]
Thanks for your kind message!

This issue is fixed in v0.9.3.
