### ISSUE TITLE
Some operating systems require a new folder/directory, others don't mount unless a directory already exists (non-universal binary)

### ISSUE THREAD

**Issue by samuelwatsonofficial** [mhx/dwarfs#202]
Hello again! At the moment I'm trying to use the dwarfs binaries (non-universal) along with a script to load a dwarfs filesystem properly *with the same script on different operating systems.* So far this has been a massive success as dwarfs works very well using the same script across windows and linux however there is a problem in that the windows binary will refuse to mount a filesystem in a folder that already exists. The binary works perfectly when making a new folder with a given name yet doing this on linux does not work. I would greatly appreaciate it if there was one way of mounting so that the same script can work on both linux and windows.
The error given when the windows binary doesn't mount is:
"
.\dwarfs prexistingfolder.dwarfs prexisting
Cannot create WinFsp-FUSE file system: mount point in use.
"
If there is anything else I can do or something I missed, I would greatly appreaciate you letting me know.
Thanks again

**Comment by mhx** [comment]
That is unfortunately how things appear to work on Windows. I'd consider the behaviour on Linux / macOS "correct" as this is how file systems have been mounted for decades. Why this is different on Windows / WinFsp, I honestly don't know.

Changing the Linux behaviour would definitely be unintuitive, so that's not going to happen. Changing the Windows behaviour is outside of the scope of DwarFS, and I'm not even sure it's something that WinFsp could actively address.

I think the easiest way to fix this in your script would be to just create a directory on non-Windows platforms before mounting.
