### ISSUE TITLE
[MacOS] DwarFS mount not seen through Finder

### ISSUE THREAD

**Issue by rraihansaputra** [mhx/dwarfs#211]
On mounting a valid DwarFS file, the files and directory can be seen on terminal and other programs (ex: VSCode) but Finder only shows the top level directories and no files.

Can provide more data/debugging if needed. AFAIK this relates to the communication between MacFUSE and DwarFS.

**Comment by mhx** [comment]
Hi and thanks for your feedback!

This is really odd. TBH, I'm not sure if I've notice this before, but I can definitely reproduce it here to some extent (I can see *all* directories, not only top level, but no files / links). I have absolutely no idea why this is happening.

I'd definitely appreciate any hints as to what could be missing in the interface between DwarFS and macFUSE.

I likely won't have time to dig into this myself before next week.

**Comment by mhx** [comment]
I've found the problem: the `getxattr()` call works quite differently on Linux and macOS.

On Linux, `getxattr()` returns `ENODATA` if an attribute doesn't exist, and that's also what the DwarFS FUSE driver returns.

On macOS, it is expected to return `ENOATTR` if an attribute doesn't exist. The macOS call doesn't even list `ENODATA`, at the same time, `ENOATTR` doesn't seem to exist on Linux.

This will be fixed in the next release.

**Comment by mhx** [comment]
You can actually work around the problem by using macFUSE's `noapplexattr` option, i.e.:

```
dwarfs image.dwarfs mountpoint -o noapplexattr
```

**Comment by mhx** [comment]
This should be fixed in v0.9.8, please re-open if there is still a problem.

**Comment by rraihansaputra** [comment]
Thank you for the quick response and the fix!
