### ISSUE TITLE
Please ignore.

### ISSUE THREAD

**Issue by throwaway-60785** [mhx/dwarfs#246]

**Comment by xsmolasses** [comment]
A fine idea, which I was immediately thinking for reducing redundancy across multiple of these split-on-block-based archives - without knowledge of or referencing other archives necessarily (there would only be a management tool subsequently taking archives’ index as input to list corresponding block files and print any mutual dependencies).

Blocks, unique by definition, could be shared and mingle with other archive sets [of block files].

For example, if I were to rename every file to its hash, any duplicate file[name]s could be this way identified; a makeshift dedupe.

(Data common in a file or among many files become a block, to my understanding.)

If a newly produced block file already exists by matching hash-as-filename in working path, then the temporary working file is deleted.

In described mode, blocks become assumed-shared block files, but without a dependency on having the shared archives in their totality.

Of course, there's bound to be gaps in my understanding of block data aggregation/compression, et cetera, that make my complement idea unfeasible.

**Comment by mhx** [comment]
I'm not sure you fully understand how DwarFS' blocks work.

While you certainly *can* take a single block and decompress it (there's even [a script for extracting individual blocks](https://github.com/mhx/dwarfs/blob/main/scripts/extract_blocks.py) included, with the main intent being evaluation of new compression algorithms), you'll be left with binary gibberish that you won't be able to interpret at all without having access to the metadata.

Again, you *can* get a full dump of the metadata (using `dwarfsck --export-metadata`) and you theoretically *could* use that to determine which blocks (note the plural) you'd need to decompress and which chunks within each block you'd need to piece together the file you're trying to read. All that *is* possible already, but it'd be a major hassle if you were trying to do it manually.

Coming back to your cold storage use case: if you mount a DwarFS image produced with a section index (anything after v0.6.0, unless the section index is explicitly disabled), *only* the metadata block will be read. Until you access *any* file, none of the data blocks will be read. So if the cold storage infra is able to handle `mmap` correctly (i.e. only retrieving data that is actually accessed), this should Just Work™. For example, I have a 60 GiB DwarFS image on a remote server with a RAID of spinning disks. I first mount the RAID to my local machine using NFS, i.e. none of the data from DwarFS image is in the local file system cache:

```
$ ll /mnt/images/astro/2024-01-18.dwarfs
.rw-r--r-- 63,754,878,297 mhx users  6 Feb 17:33 /mnt/images/astro/2024-01-18.dwarfs
```

Then I mount that 60 GiB image locally, i.e. all data transfer is over a 1 Gbps link:

```
$ dwarfs /mnt/images/astro/2024-01-18.dwarfs tmp -f
I 11:46:47.762516 dwarfs (v0.10.1-27-g3fb7af0fcb on branch mhx/dev-v0.10.2, fuse version 35)
I 11:46:47.846001 file system initialized [83.45ms]
```

As you can see, the mount finishes in less than 100 milliseconds.

Also, if I then access data in the mounted DwarFS image, it will *only* read the blocks that it has to read to reconstruct the requested data. A 50 MiB file reads in slightly less than a second, which is reasonable given that it's likely not in the cache on the remote machine and the blocks must be read from disk:

```
$ time cat 2024-01-19_03-21-14_S_gain300_offset30_-9.90_60.00s_0189.fits | wc -c   
52191360

user	0.000
system	0.018
total	0.868
```

To be honest, I don't think there's a real use case here. Also, the potential for messing up the data is much, much bigger if it's spread across dozens, hundreds or even thousands of files.

If your cold storage infra can only handle data at file granularity rather than being able to read individual chunks from an mmap'd file, it's probably better to improve that rather than adding obscure features to DwarFS (or other projects). If NFS can do this, I'm sure this is doable for cold storage, too.

**Comment by mhx** [comment]
> P. S. It seems that you cannot set the maximum depth in LZMA. I usually use --lzma2=dict=1610612736,mf=bt4,mode=normal,nice=273,depth=4294967295 to let xz to do what it can do. Increasing depth seems to only slow compression down and does not affect decompression much.

I can certainly look into exposing more of LZMA's internal options.

**Comment by silentnoodlemaster** [comment]
as a random bystander, i don't think this would make sense to implement directly into dwarfs, but maybe you could create your own implementation with the recently introduced libdwarfs

**Comment by mhx** [comment]
I *think* there might be a different project lurking in your request: I can imaging a FUSE driver that could merge a set of files (e.g. your 1 GiB blocks) according to some "index" file into a single "virtual" file that could then be `mmap`'ed by dwarfs (or any other tool than can work with subsets of larger files).
