### ISSUE TITLE
Decompress/extracting dwarfs images?

### ISSUE THREAD

**Issue by Phantop** [mhx/dwarfs#33]
I apologize if there is a way to do this and I'm just not seeing it after reading the documentation a few times over, but there doesn't appear to be any direct way to extract created dwarfs images which is a serious missing feature.

Of course, this can be done by instead mounting the FUSE filesystem and copying out, but it seems like a big oversight (assuming there is actually no way to do this and I'm not blind).

**Comment by mhx** [comment]
Hi @Phantop! Your understanding is correct, there's no `undwarfs` or anything at the moment. And yes, my suggested workaround for the time being would be to simply `rsync` the contents out of a mounted image.

This isn't really an oversight. I've thought about it before, but so far didn't consider it more of a priority than other features, primarily because there's a very usable workaround available with two simple commands, and also because unpacking is not your typical file system feature. I do see why you'd probably want it for dwarfs, though.

I'll leave this open as a reminder, but I can't make any promises as to when I get around to implementing this.

**Comment by Phantop** [comment]
Huh. Didn't actually think of it from the "this is a filesystem like any other standpoint". I've been using squashfs (and dwarfs now) as a personal stand-in for regular archives formats due to the convenience of mounting so I've started to think of them as "archives but you can mount them" at some point.

Unrelated to the issue, but just gonna say good work! Some stuff compresses so much better with dwarfs than squashfs (though the memory usage of compressing some very large files results in an OOM kill for me) and it's been pretty useful as a result.

**Comment by cipriancraciun** [comment]
Regarding decompression, perhaps a somewhat different approach might fill this need but also open up the door for new possibilities.  How about this:  instead of a decompress feature that just provides a `rsync` alternative, what if there would be a `dwarfs2tar` or `dwarfs2cpio` tool that takes a DwarFS image and pipes to `stdout` the contents of that but in a format that would be understandable by `tar` or `cpio`.

By using such a tool someone could:
* (the main use-case) extract it to somewhere on the same machine;
* pipe it over `ssh` and extract it somewhere else on a different machine;
* provide a way to inspect the contents without actually extracting it;  (for example I've written a `md5-cpio` tool that can compute MD5 and the entire SHA family over a `cpio` archive without needing to extract it;)  basically anything else would fit in here;

Consequently a `cpio2dwarfs` or `tar2dwarfs` would be nice so that one can create `dwarfs` archives without actually having the files on a real file-system.

Thus one could easily migrate (or test) from one version of DwarFS to another one.

**Comment by mhx** [comment]
@cipriancraciun, I quite like this idea, and I reckon it could be quite easy to implement using [libarchive](https://github.com/libarchive/libarchive).

**Comment by mhx** [comment]
> Unrelated to the issue, but just gonna say good work!

Thanks, much appreciated!

> [...] though the memory usage of compressing some very large files results in an OOM kill for me [...]

I have to admit I've been doing most of my compression tasks on machines with 64GB of memory, so optimizing for low memory consumption hasn't really been a priority yet. There are some knobs you might be able to turn, though. I'm not sure large files per se are an issue, but a large number of files definitely is. You might be able to tweak `--memory-limit` a bit, which determines how many uncompressed blocks can be queued. If you lower this limit, the compressor pool may run out of blocks more quickly, resulting in overall slower compression. Reducing the number of workers (`-N`) might also help a bit.

**Comment by Phantop** [comment]
> I have to admit I've been doing most of my compression tasks on machines with 64GB of memory, so optimizing for low memory consumption hasn't really been a priority yet. There are some knobs you might be able to turn, though. I'm not sure large files per se are an issue, but a large number of files definitely is. You might be able to tweak `--memory-limit` a bit, which determines how many uncompressed blocks can be queued. If you lower this limit, the compressor pool may run out of blocks more quickly, resulting in overall slower compression. Reducing the number of workers (`-N`) might also help a bit.

A small update on this (apologies that this is on an unrelated issue). Did some experimentation and found that lowering memory limit and workers works in some instances but not in others. Large files seems to be the biggest hold up, in particular an instance when I tried to put a 3.1 GB file which seemingly had no way of compressing via dwarfs with my 16 GB or memory.

What I did find instead was that using the `-l0` option works in these cases, at which point I can use `mkdwarfs --recompress`. Creating the initial image with `-S24` results in very well compressed files in these instances, the 3.1 GB file compressing down to 2.3 GB whereas the default block size for `-l0` resulted in a 2.6 GB file (which is approx what `mksquashfs -comp zstd -b 1M -Xcompression-level 22` also gave me).

**Comment by mhx** [comment]
Hi @Phantop, I just saw your reply. I've created #35 for this, as it seems unrelated to the topic of this issue.

More on-topic, I've just pushed some changes to the [next-release](/mhx/dwarfs/tree/next-release) branch that add a [`dwarfsextract`](https://github.com/mhx/dwarfs/blob/next-release/doc/dwarfsextract.md) tool. This allows for directly extracting a filesystem via

    dwarfsextract -i image.dwarfs -o output-directory

as well as on-the-fly `cpio`/`tar`/... creation from a filesystem image, e.g.:

    dwarfsextract -i image.dwarfs -o output.tar -f ustar
    dwarfsextract -i image.dwarfs -f ustar | gzip > output.tar.gz
    dwarfsextract -i image.dwarfs -f cpio | cpio -id

As this is based on [libarchive](https://github.com/libarchive/libarchive), it supports [a large variety of formats](https://www.freebsd.org/cgi/man.cgi?query=libarchive-formats&sektion=5&n=1).

Please feel free to play with this and let me know if you have any feedback.

**Comment by mhx** [comment]
Fixed in v0.4.0.
