### ISSUE TITLE
Mkdwarfs crashes when creating images using compression levels 6+

### ISSUE THREAD

**Issue by Kron4ek** [mhx/dwarfs#37]
Hello!

Mkdwarfs crashes for me when i use compression levels 6 and higher, lower levels work fine. This is the error i get:

```
** Aborted at 1616416371 (Unix time, try 'date -d @1616416371') ***
*** Signal 4 (SIGILL) (0x4b9ec2) received by PID 24703 (pthread TID 0x25a2140) (linux TID 24703) (code: illegal operand), stack trace: ***
Illegal instruction (core dumped)
```

[mkdwarfs-coredump.zip](https://github.com/mhx/dwarfs/files/6182348/mkdwarfs-coredump.zip)

I'm using the latest (0.4.1) static executables from the releases page. OS is Arch Linux.

**Comment by mhx** [comment]
Hi @Kron4ek, thanks for the report!

I think I'm pretty certain what area that is coming from. Could you please try adding `--order=similarity` to the command line? I would assume that fixes the crash. Can you please also let me know the output of `cat /proc/cpuinfo`?

**Comment by mhx** [comment]
Thanks!

Could you please try [mkdwarfs.gz](https://github.com/mhx/dwarfs/files/6183254/mkdwarfs.gz)?

The 0.4.[01] releases are the first releases to use clang/gcc's function multiversioning feature for some hot functions, optimizing them to make use of certain processor features, if available. In the coredump, I see:

```
#0  0x00000000004b9ec2 in dwarfs::find_similar_inode(unsigned long const*, std::vector<std::shared_ptr<dwarfs::inode>, std::allocator<std::shared_ptr<dwarfs::inode> > > const&, std::vector<unsigned int, std::allocator<unsigned int> > const&, long, long) [clone .arch_skylake] ()
```

So it's using the `arch_skylake` clone of the function, which is obviously not a good fit for your processor. *Why* it's using that clone, I don't know. I was under the assumption that it would only pick this clone if it's actually running on a skylake (or similar) CPU.

I've just quickly built the 0.4.1 release with `gcc` instead of `clang`, which disables the skylake clone and only leaves the `popcnt` clone in (which should be used according to your CPU flags). The difference is speed is marginal, so I'll probably eliminate the skylake stuff altogether if it's causing trouble.

**Comment by Kron4ek** [comment]
> Could you please try mkdwarfs.gz?

This build doesn't crash, thank you.

**Comment by mhx** [comment]
Brilliant. I've replaced the binary tarball on the release page with the gcc build.
