### ISSUE TITLE
folly/libfolly.so.0.58.0-dev: undefined reference to `typeinfo for snappy::Source'

### ISSUE THREAD

**Issue by RarogCmex** [mhx/dwarfs#56]
The complete build log:
[build.log.txt](https://github.com/mhx/dwarfs/files/6968954/build.log.txt)

It seems to upstream issue of Folly https://github.com/facebook/folly/issues/1583
There are fix:
https://github.com/facebook/proxygen/issues/361
It introduced when I upgrade the system.

**Comment by RarogCmex** [comment]
Also https://github.com/facebook/folly/issues/1606

**Comment by mhx** [comment]
Thanks for reporting!

As far as I can tell, this is an issue with snappy, not with folly or dwarfs.

IMHO it's silly to force `-fno-rtti` onto users of a library. Having the *option* to compile with `-fno-rtti` is absolutely fine, but I don't think a library should make this its default. (The `-fno-rtti` got added to snappy's `CMakeLists.txt` between 1.1.8 and 1.1.9.)

I could take a look at disabling snappy support in folly when using the submodule version, but that's not going to help much with an ebuild that uses a system-installed folly. This must be fixed in snappy or folly (by compiling the relevant code that links to snappy with `-fno-rtti`).

I'll close this for now as I don't think there's much I can do. Please feel free to reopen if I've missed something.
