### ISSUE TITLE
mkdwarfs help lists ZSTD minimum compression as -131072

### ISSUE THREAD

**Issue by mgord9518** [mhx/dwarfs#79]
Title pretty much explains it, version affected is v0.5.6

```
Compression algorithms:
  null     no compression at all
  lz4      LZ4 compression
               level=[0..9]
  lz4hc    LZ4 HC compression
               level=[0..9]
  zstd     ZSTD compression
               level=[-131072..22]
  lzma     LZMA compression
               level=[0..9]
               dict_size=[12..30]
               extreme
               binary={x86,powerpc,ia64,arm,armthumb,sparc}
```

**Comment by mhx** [comment]
Yeah, strange as it seems, [this is actually correct](https://github.com/facebook/zstd/blob/v1.5.2/lib/compress/zstd_compress.c#L6187). :)

`mkdwarfs` even makes the proper call to `ZSTD_minCLevel()` in order to display this number.

*Why* this choice was made and how useful these negative compression levels are at all is a different question that's probably best discussed with the Zstd folks.

**Comment by mgord9518** [comment]
Haha yeah that's super bizarre. I had zero clue ZSTD's negative compression went so far
